[package]
name        = "pr13165-package"
description = "Private-repo test package for flix#13165"
version     = "0.1.2"
flix        = "0.75.3"
repository  = "github:wstein/pr13165-package"
authors     = ["Werner Stein <werner.stein@gmail.com>"]
